### ISSUE TITLE
Handling packages with invalid `MatchSpec` (for their `dependencies` and `constrains`)

### ISSUE THREAD

**Issue by jjerphan** [conda-forge/admin-requests#1087]
### Context

Some packages published on conda-forge like `infowillow-1.6.3-pyhd8ed1ab_0.conda` use invalid `MatchSpec`.

This is for instance the case of one of its dependencies which is encoded as:

```
pillow-heif >=0.10.0,<1.0.0<py312
````

This `MatchSpec` is invalid, since the `<py312` suffix is not supported by the [`MatchSpec` specification](https://github.com/conda/conda/blob/main/conda/models/match_spec.py#L86-L165).

### Questions

 - Is this a known problem?

 - How should those packages be handled? Must they simply be removed?

 - Might some of such specifications stem from [grayskull](https://github.com/conda/grayskull) converting [PEP 508 dependency specification customs](https://peps.python.org/pep-0508/#environment-markers) from PyPI packages?

**Comment by ocefpaf** [comment]
It doesn't seem to be related to grayskull. I could not find that package either but I did find a reference to it in https://github.com/conda-forge/willow-feedstock/pull/27. It was a human mistake and one should open an issue there. BTW, this repo is not the best place this this report.

**Comment by SylvainCorlay** [comment]
I think it is a general question for conda-forge about whether it is ok to remove packages that have non-sensical specs, that could break the parsing of the channel data.

**Comment by jaimergp** [comment]
FWIW, this shouldn't be a problem in the future provided conda-build 24.7+ is in use (https://github.com/conda/conda-build/pull/5359).

**Comment by ocefpaf** [comment]
> I think it is a general question for conda-forge about whether it is ok to remove packages that have non-sensical specs, that could break the parsing of the channel data.

This happens all the time. We discussed it in element channel but I'll post here for posterity. The steps to fix it are:

1. Fix the feedstock, also open the issue there so the maintainers know of this issue.
2. Send a repodatapatch PR to fix the current package

**Comment by jjerphan** [comment]
> BTW, this repo is not the best place this this report.

Sorry for that. Where shall I report issues in the future?

**Comment by ocefpaf** [comment]
> Sorry for that

Not a problem.

> Where shall I report issues in the future?

For feedstock problems? In the feedstock. For general problems we use https://github.com/conda-forge/conda-forge.github.io.
