### ISSUE TITLE
Broken feedstock creation with v1 recipe

### ISSUE THREAD

**Issue by msarahan** [conda-forge/admin-requests#1089]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I merged a v1 recipe at https://github.com/conda-forge/staged-recipes/pull/27600. The feedstock creation didn't work as I had hoped. This could have been because:

* I [manually triggered feedstock creation](https://github.com/conda-forge/admin-requests/actions/runs/10951563368), being impatient. This seems like it happened at the same time as the scheduled run. Sad face.
* After the aborted runs (because more than one was running at a time), [the repo would be created, but the branch would not be found](https://github.com/conda-forge/admin-requests/actions/runs/10951598143/job/30408891935#step:6:1136). 
* If I created a dummy file in the repo to create the branch, then [files were missing](https://github.com/conda-forge/admin-requests/actions/runs/10951650435/job/30409036828#step:6:1123)

I manually ran several conda-smithy commands locally (guided by https://conda-forge.org/docs/user/ci-skeleton/):
* `conda-smithy init numba-cuda` where `numba-cuda` is my local folder with recipe.yaml in it. This created numba-cuda-feedstock with `conda-forge.yml` and `recipe/recipe.yaml`.
* `conda-smithy register-github .`, which didn't work, because it tried to remove a non-existent file:

```
  File "/home/msarahan/miniforge3/lib/python3.10/site-packages/git/cmd.py", line 1388, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rm --cached -- ./disabled_appveyor.yml
  stderr: 'fatal: pathspec './disabled_appveyor.yml' did not match any files'
```
* `conda-smithy rerender -c auto` - created lots of CI files. I committed and pushed these.
* The bot came behind me in https://github.com/conda-forge/admin-requests/actions/runs/10951862709/job/30409596648, and I am not sure that anything I did had any effect. At any rate, it seems like some combination of my work and the scheduled workflow has fixed things.

I hope things are all in order now. Was this a problem that ultimately arose from my stupid impatience, or might it be something related to the v1 recipe?

### Installed packages

```shell
conda list
```

### Environment info

```shell
conda info
```

**Comment by msarahan** [comment]
related: https://github.com/conda-forge/conda-forge.github.io/issues/2308

**Comment by beckermr** [comment]
Is this still broken @msarahan @wolfv or can we close this?

**Comment by jakirkham** [comment]
Has any one tried the v1 recipe in staged-recipes recently? Without that it is kind of hard to know
