### ISSUE TITLE
Support for (un)archiving feedstocks

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/admin-requests#109]
Would be useful to have an admin request here for handling archiving/unarchiving feedstocks.

**Comment by tdegeus** [comment]
That would be very welcome. I have had quite some such requests in switching to multi-output feedstocks

**Comment by jaimergp** [comment]
I wanted to get more familiar with this part of the infra, so I gave it a try and added a potential workflow for this at https://github.com/conda-forge/admin-requests/pull/532

Lmk what you think!
