### ISSUE TITLE
How to select cpu version of package during install

### ISSUE THREAD

**Issue by pplonski** [conda-forge/admin-requests#1126]
### Comment:

Thank you for your amazing work on conda-forge.

I have a question on how to select the cpu version of package during install. I would like to install [shap](https://anaconda.org/conda-forge/shap/files) which is availabe with cpu or gpu. I would like to select the cpu version, I have CUDA on my machine, but I would like to force conda to use cpu. Is there any command? I was searching on stackoverflow and asking chatgpt, but I only get answers for pytorch. And for pytorch the following command is working:

```
conda install -c conda-forge pytorch-cpu
```

but when I try to install `shap` in the similar way:
```
conda install -c conda-forge shap-cpu
```

I got information that such package is not available. However, I see builds for both cpu and gpu:

![Image](https://github.com/user-attachments/assets/2bc2e85d-db34-4d62-9953-25ad75bc8d98)
 
Thank you!

**Comment by mattwthompson** [comment]
The `pytorch-cpu` package isn't a CPU variant of a `pytorch` package, it's just a package that happens to have that sort of name, i.e. the appended `-cpu` is not parsed by in the way that it might read to a human. There probably aren't `shap-cpu` packages, unless somebody feels like making that.

What you're reaching for is build variants, which you can install with syntax that I can never find a good reference for. [Here's what is looks like in practice for a different package](https://conda.discourse.group/t/help-with-build-variants/664).

Try something like

```shell
$ micromamba install "shap=*=*cpu*" -c conda-forge
```

which, on my machine, brings down some CPU build of that package

**Comment by hmaarrfk** [comment]
We've generally preferreedyto use build strings to help this niche request. The suggestion from @mattwthompson is the right one. 

In general, we have optimized for users to automatically download the cuds version if their hardware supports it. 

You should be able, in most libraries, choose the hardware you wish to target CPU or GPU in the case that you have a cuda version installed. 

Nite we added pytorch-cpu to align with upstream naming many years ago.
