### ISSUE TITLE
noarch/nbformat-5.1.2-* issue

### ISSUE THREAD

**Issue by MSeal** [conda-forge/admin-requests#257]
I wasn't sure how to approach this issue, but from https://github.com/jupyter/nbformat/pull/217, it was shown that the https://anaconda.org/conda-forge/nbformat/files 5.1.2 release was generating inappropriate random ids. We changed 5.1.3 to generate hash ids and yanked the PyPI release. The package isn't broken per se but it's highly problematic. Would the recourse be to mark it as broken for non-technical reasons?

**Comment by SylvainCorlay** [comment]
Yes it should definitely be marked as broken.

**Comment by jasongrout** [comment]
Should 5.1.0 be marked as broken as well, then?

**Comment by MSeal** [comment]
5.1.0 was already marked as broken due to, I believe, an issue in the feedstock that populated it.

**Comment by jakirkham** [comment]
Is there anything more to do here? Or should this be closed?

**Comment by jasongrout** [comment]
It looks like 5.1.0 is marked as broken, but 5.1.2 is not marked as broken: https://anaconda.org/conda-forge/nbformat/files

As Matt says, it technically isn't broken (i.e., it installs), but it made some highly problematic choices, and we did yank it on pypi.

**Comment by jasongrout** [comment]
I went ahead and put in a PR at https://github.com/conda-forge/admin-requests/pull/534 to mark 5.1.2 as broken.
