### ISSUE TITLE
Rename / remove redis-feedstock

### ISSUE THREAD

**Issue by SimonBoothroyd** [conda-forge/admin-requests#312]
I'm trying to add a new recipe for redis (the full package, not the python wrapper) [here](https://github.com/conda-forge/staged-recipes/pull/16170) however the linter is failing as a feedstock for a duplicate (#142) `redis-py` package already exists here: https://github.com/conda-forge/redis-feedstock

Could the archived `redis-feedstock` be renamed / removed? Or is there another preferred path forward here?

**Comment by tpdownes** [comment]
@SimonBoothroyd conda-forge/staged-recipes#16170 was merged but I can't tell if it disappeared in a black hole. I, too, find it annoying to have to install `redis` itself from `defaults`.

**Comment by tpdownes** [comment]
@wolfv I cannot find the action associated with conda-forge/staged-recipes#16170 (which you merged) and determine if/how it failed. I assume it would collide with the repo linked to above.

**Comment by SimonBoothroyd** [comment]
@tpdownes because of the conflicts with existing repo's / packages we opted to just push this package as [`redis-server`](https://github.com/conda-forge/redis-server-feedstock) for now:

```conda install -c conda-forge redis-server```

**Comment by tpdownes** [comment]
Thanks. It's not great that the package name is changing to accommodate a package that was a duplicate in the first place. But at least it's there!

**Comment by jakirkham** [comment]
Is there anything left to do here?

**Comment by tpdownes** [comment]
I do not think it's great that the redis client is installed with the redis-server package especially since the feedstock READMEs are so generic. But, if the policy is that `redis-feedstock` must be archived forever in its present form, then no, I don't think there's a remaining action.
