### ISSUE TITLE
Invalid versions in conda-forge/label/broken lead to installation failure

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/admin-requests#346]
Basically `conda create -n test-env -c conda-forge/label/broken pyside2` will fail with: 
```
InvalidVersionSpec: Invalid version '2.0.0~alpha0': invalid character(s)
```

This is because In [this line](https://github.com/conda/conda/blob/477ed12b039bf10c3f6d06a14c3117fe891388f7/conda/resolve.py#L134) conda constructs a list of available packages and parses their versions in [here](https://github.com/conda/conda/blob/477ed12b039bf10c3f6d06a14c3117fe891388f7/conda/resolve.py#L805). This list contains `PackageRecord`s where the version is `version="2.0.0~alpha0"`. This string cannot be parsed according to conda's rules.

The packages that are violating the version rules (and will need to be deleted) are:

```python
[
    PackageRecord(
        _hash=3870681504580325642,
        name="pyside2",
        version="2.0.0~alpha0",
        build="py27_0",
        build_number=0,
        channel=Channel("conda-forge/label/broken/linux-64"),
        subdir="linux-64",
        fn="pyside2-2.0.0~alpha0-py27_0.tar.bz2",
        md5="934d955394d4fe55df52389c3a24fb0b",
        url="https://conda.anaconda.org/conda-forge/label/broken/linux-64/pyside2-2.0.0~alpha0-py27_0.tar.bz2",
        arch="x86_64",
        platform="linux",
        depends=("libgcc", "libxml2", "libxslt", "python 2.7*", "qt 5.6.*"),
        license="LGPL3",
        size=8482448,
    ),
    PackageRecord(
        _hash=3428084316280495246,
        name="pyside2",
        version="2.0.0~alpha0",
        build="py36_0",
        build_number=0,
        channel=Channel("conda-forge/label/broken/linux-64"),
        subdir="linux-64",
        fn="pyside2-2.0.0~alpha0-py36_0.tar.bz2",
        md5="601efc1d67cda89332fd3e51dc8f1faf",
        url="https://conda.anaconda.org/conda-forge/label/broken/linux-64/pyside2-2.0.0~alpha0-py36_0.tar.bz2",
        arch="x86_64",
        platform="linux",
        depends=("libgcc", "libxml2", "libxslt", "python 3.6*", "qt 5.6.*"),
        license="LGPL3",
        size=8474771,
    ),
    PackageRecord(
        _hash=8670771201715925028,
        name="pyside2",
        version="2.0.0~alpha0",
        build="py35_0",
        build_number=0,
        channel=Channel("conda-forge/label/broken/linux-64"),
        subdir="linux-64",
        fn="pyside2-2.0.0~alpha0-py35_0.tar.bz2",
        md5="741a030b6c25705123c8d7dd8c9e08bf",
        url="https://conda.anaconda.org/conda-forge/label/broken/linux-64/pyside2-2.0.0~alpha0-py35_0.tar.bz2",
        arch="x86_64",
        platform="linux",
        depends=("libgcc", "libxml2", "libxslt", "python 3.5*", "qt 5.6.*"),
        license="LGPL3",
        size=8478530,
    ),
]
```

Could these packages be deleted?

@beckermr recommended on [Gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=61967878197fa95a1c7ab3ee) to create an issue here.

**Comment by beckermr** [comment]
cc @conda-forge/core Any objections? These packages are ancient and uninstallable.

**Comment by chrisburr** [comment]
I would have a slight preference for moving them to a label like `conda-forge/label/broken-and-invalid` but as this are pre-releases that are really really broken I wouldn't object to them just being outright deleted if that's what people would prefer.

**Comment by beckermr** [comment]
Sounds good. We should make sure they are not on the main label as well.

**Comment by beckermr** [comment]
ok done. @basnijholt can you try again?

**Comment by basnijholt** [comment]
Great, it works now! 

Thanks a lot for the quick fix :tada:
