### ISSUE TITLE
Are broken packages supposed to be removed from main?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/admin-requests#436]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It seems that the recently marked broken qt-webengine package is being downloaded.
![image](https://user-images.githubusercontent.com/90008/167041739-1db9541b-2d17-4b40-ad82-82c975284ef3.png)

My hunch is that it is the main label isn't being removed.

https://anaconda.org/conda-forge/qt-webengine/files

Documentation states that they should be removed from the `main` label.

https://conda-forge.org/docs/orga/guidelines.html?highlight=broken#fixing-broken-packages

### Installed packages

```shell
qt-webengine
```

### Environment info

```shell
mamba
```

**Comment by isuruf** [comment]
No, that's how this works. See the announcement in https://conda-forge.org/docs/user/announcements.html
