### ISSUE TITLE
Token reset for nibabel-feedstock

### ISSUE THREAD

**Issue by effigies** [conda-forge/admin-requests#568]
### Comment:

Following up on https://github.com/conda-forge/status/issues/137, the nibabel-feedstock is unable to publish its package with error "invalid feedstock token".

xref https://github.com/conda-forge/nibabel-feedstock/issues/36

**Comment by jakirkham** [comment]
Please follow [these instructions]( https://github.com/conda-forge/admin-requests#reset-your-feedstock-token )

**Comment by effigies** [comment]
Ah, thanks. Apologies for the noise.
