### ISSUE TITLE
Token reset for datavzrd-feedstock

### ISSUE THREAD

**Issue by johanneskoester** [conda-forge/admin-requests#580]
### Comment:

The [datavzrd-feedstock](https://github.com/conda-forge/datavzrd-feedstock) seems to be affected by the token issue (https://github.com/conda-forge/status/issues/137), see [the build logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=638867&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=765).

As instructed in https://github.com/conda-forge/status/issues/137, this is the request for resetting the token.

**Comment by chrisburr** [comment]
See https://github.com/conda-forge/admin-requests#reset-your-feedstock-token for how to make the PR to reset the token.

**Comment by chrisburr** [comment]
The PR needs to be made to `conda-forge/admin-requests`

**Comment by johanneskoester** [comment]
Oh! that makes a lot more sense... Sorry
