### ISSUE TITLE
Is it possible to overwrite a version tag?

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/admin-requests#662]
### Comment:

I've looked through the [broken packages docs ](https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages) but am not finding an answer to whether I can overwrite/rename a mistaken package version:

In this case there are no issues with the dependencies, we just got the version tag wrong. This causes issues in scripts that sort calver version strings (see below we should've published `2023.01.04` not `2023.1.4`:

```
pangeo-dask               2022.12.17      hd8ed1ab_0  conda-forge         
pangeo-dask                 2023.1.4      hd8ed1ab_0  conda-forge         
pangeo-dask               2023.01.11      hd8ed1ab_0  conda-forge         
pangeo-dask               2023.01.13      hd8ed1ab_0  conda-forge
```
In this case it would also be ok to delete the `2023.1.4` version entirely since this is a metapackage that simply pins other package combinations over time...

feedstock issue: https://github.com/conda-forge/pangeo-dask-feedstock/issues/110

**Comment by chrisburr** [comment]
> Or ... try to see if it is possible to rename using a repodata patch

It's not possible to 😄
