### ISSUE TITLE
Deleting a single release on anaconda.org for https://anaconda.org/conda-forge/interpret

### ISSUE THREAD

**Issue by paulbkoch** [conda-forge/admin-requests#672]
### Comment:

A few days ago I published a new package on conda-forge (https://anaconda.org/conda-forge/interpret).  My intention was to make this package a noarch package.  For reasons that aren't important to get into here, I made the initial release "win-64" with the intention of putting out a noarch update shortly after the feedstock was created.  That noarch update has been released.  I've noticed now though that I can't get rid of the "win-64" platform label on https://anaconda.org/conda-forge/interpret

In my local environment I noticed that the conda channels list specific architectures first, before the noarch "platform", I'm concerned that on Windows it might attempt to download the obsolete version first before the newer noarch package.  Even if that is not the case, this is the kind of thing that feels like it might be an issue someday for someone with some kind of configuration that I'm not currently aware could exist.

I think the safest thing to do here would be to delete the initial win-64 specific file on anaconda.org (FILE: win-64/interpret-0.2.7-py38haa244fe_0.conda).  At this point nobody will have taken a dependency on that file, and there are very few downloads (20-ish).  I imagine all of those have been from automated systems so far and from my own testing.

I did note there is a process to mark packages as "broken" ( https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages ).  Is that the right approach here?  Would that be sufficient to remove the "win-64" platform label?  Outright deletion still feels like a cleaner solution to me given this isn't depended on yet.

**Comment by hmaarrfk** [comment]
Please try the broken approach for now, I believe it will resovle your issues.

**Comment by paulbkoch** [comment]
Thanks @hmaarrfk -- I submitted the PR.

**Comment by paulbkoch** [comment]
Hi @hmaarrfk --

Well.. I see the broken label now on https://anaconda.org/conda-forge/interpret , but it's still labeled as "win-64" under installers.  🤷

**Comment by hmaarrfk** [comment]
but if you clean your environment hard enough,

```
conda install -c conda-forge interpret
```
should pull from the noarch package right?

**Comment by paulbkoch** [comment]
Presumably, yes.

**Comment by hmaarrfk** [comment]
right. unless the really try, they shouldn't bee able ot download from other than main.

**Comment by hmaarrfk** [comment]
let us know if you have any additional issues.

**Comment by paulbkoch** [comment]
Ok, thanks for your help @hmaarrfk

**Comment by hmaarrfk** [comment]
Thank you for taking the time to read the docs ^_^
