### ISSUE TITLE
R-forge token reset not fully successful

### ISSUE THREAD

**Issue by dpryan79** [conda-forge/admin-requests#743]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

R-forge-feedstock is currently failing because the packages posted to staging can't be copied over successfully (Xref: https://github.com/conda-forge/r-forge-feedstock/issues/8 ). We've tried resetting the token to clear this up ( https://github.com/conda-forge/admin-requests/pull/741 ), but the problem persists. This same issue arose last year ( https://github.com/conda-forge/admin-requests/pull/496 ). I suspect someone will either need to manually create a project on Travis or temporarily hack around this issue like last year. 

@beckermr You temporarily worked around this issue last year, do you have any thoughts about how to best proceed?

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by beckermr** [comment]
You should be able to use a file like this now:

```
# --without-travis
r-forge
```

and the token reset will skip travis. Submit a new PR with that and I'll merge it.

**Comment by dpryan79** [comment]
Xref: https://github.com/conda-forge/admin-requests/pull/745

**Comment by beckermr** [comment]
OK. I had to fix some bugs but this is working and retrying correctly. I am going to close this issue but if you are still having trouble, let me know!

**Comment by dpryan79** [comment]
This seems to have worked, thanks @beckermr !
