### ISSUE TITLE
Update CI tokens for `jupyterlab-github-feedstock`

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/admin-requests#782]
### Comment:

As suggested over on https://github.com/conda-forge/jupyterlab-github-feedstock/issues/4#issuecomment-1664800521 , @conda-forge/jupyterlab-github isn't currently uploading after two build number attempts due to an invalid token.

Is this the right place to ask? Is there a bot command to streamline this?

Thanks!

**Comment by bollwyvl** [comment]
@conda-forge/core any thoughts?

**Comment by beckermr** [comment]
See the readme on this repo for how to make the pr to refresh the tokens.

**Comment by bollwyvl** [comment]
Ah, thanks!
