### ISSUE TITLE
Should mislabeled `noarch` packages be marked as `broken`?

### ISSUE THREAD

**Issue by mfansler** [conda-forge/admin-requests#924]
### Comment:

The [`r-textrecipes-feedstock`](https://github.com/conda-forge/r-textrecipes-feedstock) has been generating "`noarch`" builds which were actually getting compiled. Effectively, all builds since v0.2.0 are really `linux-64`. This has been ongoing since v0.2.0 of this package (3 years 9 months ago) and is only being corrected now in https://github.com/conda-forge/r-textrecipes-feedstock/pull/28.

What is the proper solution here? Should we mark these builds as `broken`? or is there a way to move them into the `linux-64` subdirectory?

**Comment by xhochy** [comment]
Yes, you should mark them as broken. We cannot move packages between architectures using repodata patching.
